packages:
  - website
  - packages/*

catalogMode: prefer

onlyBuiltDependencies:
  - esbuild
  - lightningcss

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  react: ^19.2.0
  react-dom: ^19.2.0
  "@types/react": ^19.2.0
  "@types/react-dom": ^19.2.0
  three: ^0.184.0
  "@types/three": ^0.184.0
  "@react-three/fiber": ^9.6.1
  "@react-three/drei": ^10.7.7
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
