import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    // Generated by the TanStack Router plugin on every build in its own style;
    // never hand-formatted (see AGENTS.md). Exclude so `vp check` and the build agree.
    ignorePatterns: ["**/routeTree.gen.ts"],
  },
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
    overrides: [
      {
        files: ["packages/phone-3d/**"],
        plugins: ["typescript", "react"],
      },
    ],
  },
  run: {
    cache: true,
  },
});
