/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PhoneRouteImport } from "./routes/_phone";
import { Route as PhoneIndexRouteImport } from "./routes/_phone/index";

const PhoneRoute = PhoneRouteImport.update({
  id: "/_phone",
  getParentRoute: () => rootRouteImport,
} as any);
const PhoneIndexRoute = PhoneIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PhoneRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof PhoneIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof PhoneIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_phone": typeof PhoneRouteWithChildren;
  "/_phone/": typeof PhoneIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/";
  id: "__root__" | "/_phone" | "/_phone/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PhoneRoute: typeof PhoneRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_phone": {
      id: "/_phone";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof PhoneRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_phone/": {
      id: "/_phone/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof PhoneIndexRouteImport;
      parentRoute: typeof PhoneRoute;
    };
  }
}

interface PhoneRouteChildren {
  PhoneIndexRoute: typeof PhoneIndexRoute;
}

const PhoneRouteChildren: PhoneRouteChildren = {
  PhoneIndexRoute: PhoneIndexRoute,
};

const PhoneRouteWithChildren = PhoneRoute._addFileChildren(PhoneRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  PhoneRoute: PhoneRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
